# .streamlit/secrets.toml

alpaca_api_key = "PKUY243PPUK29FFEBO0W"
alpaca_secret_key = "buEgMnp7k6GoreDYy7SC63zHV4YCErrKy9EKzCJz"
email_from = "reece.flew@gmail.com"
email_to = "reece.flew@gmail.com"
email_pass = "Hq1569801"
email_host = "smtp.gmail.com"
email_port = 465
